### ISSUE TITLE
change readme.md to not have comment

### ISSUE THREAD

**Issue by rmflight** [biodataganache/MDRpred#5]
markdown looks at anything with # as a header, so for the markdown version, remove those lines. You might want to have the readme.txt as the current one

**Comment by biodataganache** [comment]
Thanks. Still a novice here :)

**Comment by biodataganache** [comment]
Done

**Comment by rmflight** [comment]
I know. Lean some markdown, you might never write in a WYSIWYG editor again ....

**Comment by rmflight** [comment]
BTW, the readme.txt is much nicer on the eyes
